[build]
 # Default build command.
 # command = "echo 'default context'"
 #CI='' npm run build
 CI= react-scripts build


# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200